spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
eureka:
  client:
    service-url: 
        defaultZone: http://localhost:8081/eureka/