spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**
      - id: student
        uri: lb://student
        predicates:
        - Path=/student/**
      - id: teacher
        uri: lb://teacher
        predicates:
        - Path=/teacher/**
      - id: course
        uri: lb://course
        predicates:
        - Path=/course/**
  profiles:
    active: "@profiles.active@"
