version: '3.8'
services:
  school: 
    build: .
    image: web
    container_name: web
    ports:
      - '8081:8081'
    depends_on:
     - mysql
     - redis
    networks:
     - front
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: school
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    networks:
     - front
  redis: 
    image: redis
    container_name: redis
    networks:
     - front
networks:
  front:
    driver: bridge