server:
  port: 8081

spring:
  application:
    name: Eure
  profiles:
    active: "@profiles.active@"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
